server:
  port: 16000

spring:
  #application:
   # name: gulimall-search  # 服务名

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #默认情况下json时间格式带有时区，并且是世界标准时间，和我们的时间差了八个小时
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    jest:
      uris[0]: http://192.168.101.128:9200  # http://
      #
      # 数组 uris，不写[0][1]这种，后面数据直接用, 隔开即可
       # - http://192.168.128.130:9200

