spring:
  cloud:
    gateway:
      routes:
        - id: pms_route
          uri: lb://gulimall-pms
          predicates:
            - Path=/pms/**, /api/index/**, /api/item/**
          filters:
            # {} 是用来取值的
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: oms_route
          uri: lb://gulimall-oms
          predicates:
            - Path=/oms/**
            # filters:
            # - AddResponseHeader=heyijie,666
        - id: sms_route
          uri: lb://gulimall-sms
          predicates:
            - Path=/sms/**
        - id: ums_route
          uri: lb://gulimall-ums
          predicates:
            - Path=/ums/**, /api/ums/**
          filters:
            # {} 是用来取值的
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: gulimall-wms_route
          uri: lb://gulimall-wms
          predicates:
            - Path=/wms/**
        - id: gulimall-search_route
          uri: lb://gulimall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}