# mysql数据库连接
spring:
  datasource:
    #useUnicode=true&
    url: jdbc:mysql://192.168.101.128:3306/guli_sms?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    # Hikari是Spring Boot 2.0之后默认整合的数据库连接池，比druid更快的数据库连接池
    # 数据源类型
